# Generated by Django 4.1.3 on 2022-12-14 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images_Article',
        ),
    ]
