# Generated by Django 4.1.3 on 2022-12-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_delete_images_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.ImageField(default=None, upload_to='Article/%Y/%m'),
        ),
    ]
