# Generated by Django 4.1.3 on 2022-12-15 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_article_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='articles',
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='myApp.category'),
        ),
    ]
