# Generated by Django 4.1.3 on 2022-12-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_alter_article_location'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscriber_category',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='subscriber_category',
            name='subscriber',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='Subscriber',
        ),
        migrations.RemoveField(
            model_name='subscriber_category',
            name='subscribed_time',
        ),
        migrations.RemoveField(
            model_name='subscriber_category',
            name='category',
        ),
        migrations.AddField(
            model_name='subscriber_category',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='myApp.category'),
        ),
    ]
