# Generated by Django 4.1.3 on 2022-12-17 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_alter_subscriber_category_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber_category',
            options={'ordering': ['subscriber']},
        ),
        migrations.RenameField(
            model_name='subscriber_category',
            old_name='category',
            new_name='categories',
        ),
    ]
