# Generated by Django 4.1.3 on 2022-12-17 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_alter_subscriber_category_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscriber_Category',
            new_name='Subscriber',
        ),
    ]
