# Generated by Django 4.1.3 on 2022-12-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_rename_subscriber_category_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
